### PR TITLE
fix: loader.js in README.md should include /image path

### PR DESCRIPTION
**Pull request by ChiefORZ**

### CODE REVIEW

**Comment by Cizzl** [comment]
@andrasbacsai please merge 💯

**Comment by DanielRiveraHQ** [comment]
@andrasbacsai do you think we can merge this one? 🙏 
I spent a few hours trying to figure out why it wasn't working.

**Comment by rampollaluis** [comment]
Commenting for visibility to the issue. Was about to open a pull request for this exact same issue. Spent a few minutes figuring it and and had to go into the index.js and see how it handles the files to figure it out.

**Review by mejiasd3v — APPROVED** [review]

**Comment by andrasbacsai** [comment]
Thank you for the PR (sorry for the super late reply).

**Pull request merged**
